# Generated by Django 4.2.13 on 2024-07-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='query',
            new_name='search_box',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='result',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='timestamp',
        ),
    ]
